blank_issues_enabled: false
contact_links:
  - name: Questions and Help (Discord)
    url: https://discord.com/invite/cpYkJzd
    about: This issue tracker is for bugs only, not general support questions. Please join our Discord server if you have any question and/or need help.
  - name: Questions and Help (Telegram)
    url: https://t.me/pokehunt_xyz
    about: This issue tracker is for bugs only, not general support questions. Please join our Telegram chat if you have any question and/or need help.
  - name: ðŸš€ Feature Request
    url: https://github.com/pokehunt-xyz/website/discussions/new?category=feature-requests
    about: Remember to search for existing feature requests and "up-vote" any you like